# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ff13ff4b7faebb6d8f5bf8ed35e6dcb76f17a715a4709fc40f9c9cc49165dfdbe861b26e77a3faedc71ac61af2ee83f811ffb97c5c25d543c233b4889a5864f

test:
  secret_key_base: 656460d13f76f9381b4554661074c4e3759e40141c0273e34f05093d47b6795bbb47a26b56fadcd94e732b82ddd2104029886d244e914104ef775301df3be7f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
